### ISSUE TITLE
there is a page

### ISSUE THREAD

**Issue by ayqy** [samacs/simple_html_dom#6]
src:

```
echo file_get_html('http://fex.baidu.com/')->find('title', 0)->plaintext;
```

I got an error:

>  Trying to get property of non-object

other url works well, but this one fails.

**Comment by dmitriyButeiko** [comment]
You should use this code:
`$htmlResponse = file_get_contents('http://fex.baidu.com/');
$htmlResponseDomObject = str_get_html($htmlResponse);
$htmlResponseDomObject->find('title', 0)->plaintext;`

**Comment by ayqy** [comment]
Thanks for help, an old issue lives so long, other PHP community modules seem to like this one as well, So we have tossed out and picked up NodeJS ecosystem now.
